to_terminal = {
    "INTEGER" : "num",
    "CHARACTER" : "character",
    "INT" : "vtype",
    "CHAR" : "vtype",
    "BOOLEAN" : "vtype",
    "STRING" : "vtype",
    "TRUE" : "boolstr",
    "FALSE" : "boolstr",
    "LITERAL" : "literal",
    "ID" : "id",
    "IF" : "if",
    "ELSE" : "else",
    "WHILE" : "while",
    "CLASS" : "class",
    "RETURN" : "return",
    "ADD" : "addsub",
    "SUB" : "addsub",
    "MUL": "multdiv",
    "DIV": "multdiv",
    "ASSIGN": "assign",
    "COMP": "comp",
    "SEMI": "semi",
    "LSCOPE" : "lbrace",
    "RSCOPE": "rbrace",
    "LPAREN": "lparen",
    "RPAREN": "rparen",
    "COMMA": "comma"
}